name: Synchronize k8s.gcr.io/kube-controller-manager:v1.18.3
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        run: |
          bash ./sync.sh k8s.gcr.io kube-controller-manager:v1.18.3
