name: Deploy Synchronize Jobs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Jobs
        run: |
          bash ./build-jobs.sh

      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: false
          REPOSITORIES: |
            mirrorspro/docker.bot
          WORKFLOW_FILES: |
            workflows=.github
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
